# Generated by Django 3.1.1 on 2020-12-15 02:48

from django.db import migrations
import investpy as inv
import pandas as pd


def update_model(apps, schema_editor):
    Stock = apps.get_model("stocks", "Stock")
    stocks = inv.get_stocks("brazil")
    for index, stock in stocks.iterrows():
        new_stock = Stock(symbol=stock.symbol, name=stock["name"], price=0.00)
        new_stock.save()


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0003_stock_price"),
    ]

    operations = [migrations.RunPython(update_model)]
