# Generated by Django 3.1.1 on 2020-12-20 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0004_auto_20201215_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_min', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('price_max', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('stock', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='stocks.stock')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
