# Generated by Django 3.1.1 on 2020-12-20 21:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20201215_0003'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockuser',
            unique_together={('stock', 'user')},
        ),
    ]
